# Generated by Django 5.1.4 on 2025-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0002_friend_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friend', to='mychatapp.friend'),
        ),
    ]
