# Generated by Django 5.1.4 on 2025-05-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0006_message_receiver_message_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('receiver_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_request', to='mychatapp.profile')),
                ('sender_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_request', to='mychatapp.profile')),
            ],
        ),
    ]
